server:
  port: 8080
  servlet:
    context-path: /api

spring:

  session:
    timeout: 5m

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      show-sql: true
      properties:
        hibernate:
          format-sql: true

logging:
  level:
    org.springframework.session: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.security: DEBUG

cors:
  allowedOrigin: http://localhost



