server:
  port: 8080
  servlet:
    context-path: /api

spring:

  application:
    name: cloud-storage

  session:
    store-type: redis
    timeout: 30m

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


  minio:
    url: ${MINIO_ENDPOINT}
    accessKey: ${MINIO_USER}
    secretKey: ${MINIO_PASSWORD}
    bucket-name: user-files
    directory-splitter: /
    keep-file: .keep

  cors:
    allowedOrigin: http://localhost
